project_name: wd-go
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ldflags:
      - -s -w -X main.version=v{{.Version}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - bash-zsh-support
      - fish-support
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    # Repository to push the tap to.
    tap:
      owner: quackduck
      name: homebrew-tap

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/quackduck/warpdrive-go"

    # Your app's description.
    # Default is empty.
    description: "Warp across the filesystem instantly"
    caveats: "For bash or zsh, put something like this in a profile file (like ~/.bash_profile or ~/.zshrc):\n. #{etc}/profile.d/wd.sh"
    install: |
      bin.install "wd-go"
      fish_function.install "fish-support/wd.fish"
      fish_function.install "fish-support/wd-go_on_prompt.fish"
      (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
